DROP TABLE IF EXISTS dogs;
DROP TABLE IF EXISTS cats;
DROP TABLE IF EXISTS chairs;
DROP TABLE IF EXISTS beers;
DROP TABLE IF EXISTS books;

CREATE TABLE dogs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  weight TEXT
);

CREATE TABLE cats (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  lives INTEGER NOT NULL,
  favorite_food TEXT
);

CREATE TABLE chairs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  legs INTEGER NOT NULL,
  has_wheels BOOLEAN DEFAULT FALSE
);

CREATE TABLE beers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  color TEXT,
  flavor TEXT
);

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  page_count INTEGER NOT NULL,
  author TEXT
);
